Added new endpoint umls-auth to validate umls key.
hubmapconsortium/gateway pull request #313
Opened 2024-04-17 18:37 UTC by DerekFurstPitt

Added new endpoint umls-auth to validate umls key. 

Added accompanying config values to app.cfg.example

2024-04-18 21:35 UTC, yuanzhou requested changes

2024-04-18 21:35 UTC, yuanzhou commented on hubmap-auth/src/app.py
> +    response_404 = make_response(jsonify({"message": "ERROR: Not Found"}), 404)
We should remove the use of 400 and 404 here, will never really happen. And the users will only get 500. 404 can happen when the auth passes and the requested file doesn't exist on file system, but not from here.

2024-04-18 21:35 UTC, yuanzhou commented on hubmap-auth/src/app.py
> +        return response_400
When the UMLS key is not provided in the URL, we should consider this as 401. Plus returning 400 will become 500.

2024-04-18 21:35 UTC, yuanzhou commented on hubmap-auth/src/app.py
> +        return response_400
As long as the sub-request gets to this `/umls_auth` endpoint, this `orig_uri` won't be `None`. So no need to check here, plus returning 400 will become 500 and cause confusions.

2024-04-19 01:21 UTC, DerekFurstPitt commented
@yuanzhou requested changes applied

2024-04-22 21:39 UTC, yuanzhou commented
I had tested on DEV, will go to `main` directly since we'll only deploy to PROD for now.

2024-04-22 21:39 UTC, yuanzhou approved these changes

2024-04-23 00:09 UTC, merged